from sqlalchemy.orm import Session

from app.models.news import News
from app.models.user import User
from app.models.user_preferences import UserPreferences

from app.services.email_service import send_email

from app.crud.notification import (
    create_notification,
    notification_exists,
)


def create_notifications_for_news(
    db: Session,
    news: News,
):
    preferences = (
        db.query(UserPreferences)
        .filter(
            UserPreferences.notification_enabled.is_(True)
        )
        .all()
    )

    for preference in preferences:

        # Category preference check
        if (
            not preference.categories
            or news.category not in preference.categories
        ):
            continue

        # Region preference check (case-insensitive)
        news_region = (news.region or "").lower()

        user_regions = [
         region.lower()
         for region in preference.regions
        ]

        if (
         not preference.regions
         or news_region not in user_regions
        ):
         continue

        # Determine whether the news is important enough
        important_categories = {
    "AI",
    "Security",
    "Framework",
    "Developer Tools",
    "Cloud",
    "DevOps",
        }

        minimum_score = preference.minimum_importance_score or 0

        if news.importance_score is not None:
           is_important = (
           news.importance_score >= minimum_score
         )
        else:
           is_important = (
           news.category in important_categories
        )

        if not is_important:
         continue

        # Prevent duplicate notification
        if notification_exists(
            db=db,
            user_id=preference.user_id,
            news_id=news.id,
        ):
            continue

        message = (
            f"New {news.category} news detected: "
            f"{news.title}"
        )

        create_notification(
            db=db,
            user_id=preference.user_id,
            news_id=news.id,
            message=message,
        )
        should_send_email = False

        if news.importance_score is not None:
          should_send_email = (
           news.importance_score >= 8
           or news.risk_level in ["High", "Critical"]
        )
        else:
          should_send_email = news.category in {
        "AI",
        "Security",
        "Framework",
        "Developer Tools",
        }
        # Send email only for important news
        if (
            preference.email_notification_enabled
            and should_send_email
        ):

            user = (
                db.query(User)
                .filter(User.id == preference.user_id)
                .first()
            )

            if not user:
                continue

            emoji = {
                "Security": "🚨",
                "AI": "🤖",
                "Cloud": "☁️",
                "DevOps": "⚙️",
                "Developer Tools": "🛠️",
                "Framework": "📦",
                "Software": "💻",
                "Mobile": "📱",
                "Business": "📈",
                "Gaming": "🎮",
            }.get(news.category, "📰")

            subject = (
                f"{emoji} TechPulse AI | "
                f"{news.category} - "
                f"{news.title[:60]}"
            )

            try:
                send_email(
                    to_email=user.email,
                    subject=subject,
                    body=f"""
<html>
<body style="font-family:Arial,sans-serif;background:#f4f6f8;padding:30px;">

<div style="max-width:650px;margin:auto;background:white;border-radius:12px;padding:30px;border:1px solid #e5e7eb;">

<h1 style="color:#2563eb;margin-bottom:0;">
🚀 TechPulse AI
</h1>

<p style="color:#6b7280;margin-top:5px;">
Technology Intelligence Platform
</p>

<hr style="margin:25px 0;">

<h2>New {news.category} Alert</h2>

<p>
<strong>Title</strong><br>
{news.title}
</p>

<p>
<strong>Importance Score</strong><br>
⭐ {
    f"{news.importance_score}/10"
    if news.importance_score is not None
    else "Not analyzed"
}
</p>

<p>
<strong>Risk Level</strong><br>
{
    news.risk_level
    if news.risk_level
    else "Not analyzed"
}
</p>

<p>
<strong>Summary</strong><br>
{news.summary or "No summary available."}
</p>

<p>
<strong>Affected Technologies</strong><br>
{", ".join(news.affected_technologies) if news.affected_technologies else "Not specified"}
</p>

<p>
<strong>Recommended Action</strong><br>
{news.recommended_action or "No recommendation available."}
</p>

<p style="margin-top:30px;">
<a href="{news.url}"
style="
background:#2563eb;
color:white;
padding:12px 18px;
text-decoration:none;
border-radius:8px;
display:inline-block;
">
Read Full Article
</a>
</p>

<hr style="margin-top:30px;">

<p style="font-size:13px;color:#9ca3af;">
This email was automatically generated by TechPulse AI according to your notification preferences.
</p>

</div>

</body>
</html>
""",
                )

            except Exception as e:
                print(
                    f"Email notification failed for user "
                    f"{user.id}: {e}"
                )